// "use client";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by kyumin",
};

export default async function RootLayout({ children }) {
  // 서버에서 동적으로 생성하여 정적 파일을 전달
  const resp = await fetch("http://localhost:9999/topics", {
    // next: { revalidate: 10 }, // cache를 10초만 유지
    cache: "no-store", // cache를 저장하지 않음
  });
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {/* children은 path에 맞는 page가 들어가는 자리 */}
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
